import java.util.Scanner;

public class Main
{
    public static void main(String[] args)
    {
        System.out.println(x;"Enter first number");
        int firstNum = myobj.nextInt();

        System.out.println(x;"Enter second number");
        int secondNum = myobj.nextInt();

        System.out.println(x;"Enter third number");
        int thirdNum = myobj.nextInt();

        //System.out println("largest number:")

        // int largest = 0
        // if (firstNum >= secondNum && firstNum > thirdNum)
        // {
        //     largest = firstNum
        // }
        // if (secondtNum >= firstNum && firstNum > thirdNum)
        // {
        //     largest = firstNum
        // }
        // if (firstNum >= secondNum && firstNum > thirdNum)
        // {
        //     largest = firstNum
        // }
    }
}